before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends latexmk
  texlive-fonts-extra texlive-fonts-recommended texlive-latex-base texlive-latex-extra
  texlive-latex-recommended
script:
- mkdir _build
- latexmk -pdf -outdir=_build SeniorThesisProposal.tex
deploy:
  provider: releases
  api_key:
    secure: pTrvwhewWU33nrXF3qYbzttpxKNvTT0gbqpk4PASs/dTmb3iIoOt86mZfdn7NOnhS2C6icjW01VH9/Wk+NWOK4n+zRpoqyKHEnBBg+kC7ht8RHCO7j1oZIeNVQcFlHxjjqBEAiDyistKoK0uQuHv7BEVpG557VbWFtf5Y48VL+mRAQC2D2IEQhtij0QJn2Dt84DOhdwdrrYVNYhtcdboioX9Z+6DD/D+S79ZkuPbUpsK8M3km9UeJplWZ9uoDhM3Wi0HN5CntREFTNMDsbywGic7N6PjKS+FZkf0155SkPJq3sPqIEZMtoHa+O+g4Qtconoh5iHeQhQOChPIq42JaikZ6D+ARrmVBLP5VMT/whYjIP3w4w8JbYbBJVVVXvALmPLYrg/sYFv4rfGPzjBy4Se6/uV49sB4CmGeo3vYrerP11OyH9PHSRWg/DPoARALg6vqNPViGXGf903Ixc6l3f7HXKK8j83gwkb7f+hkpCR6SAW+OEoeR5/PCe1gWluFKtsJPfka1IJ3pIZ85f8UNfwXEAzgc70B50YakKXpPKNRjiV2XVctHtXvCjX0lbhuZ/Vzpl2iXzM8U6LEzlgLpt6RZnfPkHwqW/g3ZwAlTJXPDd+reSM4ckoBoENlewm3J28RwwTD1fIOVg9BTFRModdhChRzkY9ouJoHJ3ueGPY=
  file: _build/SeniorThesisProposal.pdf
  skip_cleanup: true
  on:
    tags: true
